### PR TITLE
Can you remove the fork please?

### PR DESCRIPTION
**Pull request by fomahaut**
@ansgarschulte sorry to bother you, because of some copyright and license trouble, I need delete my repository and its forks. I know it's an impolite asking, but it would be a really huge help if you can remove this fork on GitHub. It's really important to me, hope you can help me. Thank you.

### CODE REVIEW

**Comment by ansgarschulte** [comment]
What is the problem with copyright?

**Comment by fomahaut** [comment]
It's all my fail. I didn't read my contract seriously when I published this repository, and when I read it these days, I found I had trouble. My lawyer said the company have ALL copyright with anything I had done, so the correct copyright owner is my company, not me. He suggest me remove it to avoid litigation. I would be very grateful if you can help me. It wont take you any trouble because we are in different country, and it's all my fail :(. Sorry about this again.

**Comment by ansgarschulte** [comment]
Ok. No Problem. I will delete it.

**Comment by ansgarschulte** [comment]
or what about this: I added the iOS part in my repo and I do not need Android part at all. iOS part is written by my hands. So I will delete the Android part here. Ok?

**Comment by fomahaut** [comment]
Sure, that's great. Thanks a lot for this.

**Comment by fomahaut** [comment]
BTW, can you also remove the git history please? I don't know it would be trouble or not. Thanks your friendly again!

**Comment by ansgarschulte** [comment]
delete history

**Comment by fomahaut** [comment]
Thank you! sorry for wasted your time.

**Comment by ansgarschulte** [comment]
No Problem

**Pull request closed without merging**
